---
- name: Start screen with rs232 and vm with qm
  hosts: test_conference
  become: true
  tasks:
    - name: Ensure coreutils is installed (provides stty)
      apt:
        name: coreutils
        state: present
      become: true

    - name: Configure serial port /dev/ttyUSB0 with stty
      shell: stty -F /dev/ttyUSB0 9600 cs8 -cstopb -parenb

    - name: Send the .bin file to /dev/ttyUSB0
      shell: cat /root/binary/start_screen.bin > /dev/ttyUSB0
    
    - name: Start the Proxmox VM using qm
      shell:
        cmd: "qm start {{ vmid }}"
      args:
        executable: /bin/bash
      vars:
        vmid: 100
      register: start_vm_output

    - name: Display the output of the qm start command
      debug:
        var: start_vm_output.stdout

